# Generated by Django 5.1 on 2024-08-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_profile_profile_pic_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_field',
            new_name='date_added',
        ),
    ]
